### ISSUE TITLE
Chat Error

### ISSUE THREAD

**Issue by a-ja** [KKosyfarinis/Xssentials#1]
[16:15:27 ERROR]: Could not pass event AsyncPlayerChatEvent to Xssentials v0.1.5.2-beta.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1307) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1245) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_141]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
        at com.kkosyfarinis.spigot.xssentials.events.EventOnPlayerChat.onPlayerChat(EventOnPlayerChat.java:116) ~[?:?]
        at com.kkosyfarinis.spigot.xssentials.EventListener.onPlayerChat(EventListener.java:92) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        ... 11 more

**Comment by KKosyfarinis** [comment]
Hello there and thanks for the bug report. Turns out I forgot to create a default groups.yml. There's a quick fix that you can do to fix that, you can either do 
```
/prefix group [groupName] [prefix]
```
or copy this to /plugins/Xssentials/groups.yml
```yaml
group:
  owner:
    chat:
      prefix: "Prefix"
      suffix: "Suffix"
  member:
    chat:
      prefix: "Prefix"
      suffix: "Suffix"
```

I will update the plugin later today and add a default groups configuration to fix that issue.

**Comment by a-ja** [comment]
Thanks it works now 👍
