### ISSUE TITLE
Chat Error (still)

### ISSUE THREAD

**Issue by TheLukeGuy** [KKosyfarinis/Xssentials#2]
Heyo! I left a review on Spigot saying that this is a cool plugin but needs work. I used it anyway because Essentials has too much and other alternatives too little. I ran into one chat bug that is really annoying me. I saw the last issue and that fix still didn't work. I have groups, all with prefixes and I have "" in the groups.yml for the suffixes. Here's the Java stacktrace.

`[20:10:57 ERROR]: Could not pass event AsyncPlayerChatEvent to Xssentials v1.0-pre.4
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.12.2.jar:git-Paper-1218]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1346) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1261) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1218]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at com.kkosyfarinis.spigot.xssentials.User.initializeUser(User.java:51) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.User.<init>(User.java:34) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.events.EventOnPlayerChat.onPlayerChat(EventOnPlayerChat.java:25) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.EventListener.onPlayerChat(EventListener.java:72) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.2.jar:git-Paper-1218]
	... 12 more
`

groups.yml DOES exist in the parent Xssentials directory but it still throws a NullPointerException. Here is my groups.yml in case that matters. [(I put it on Hastebin because the markdown formatting was driving me crazy)](https://hastebin.com/raw/devirinusu)

I hope you can fix this as it's really annoying and I have my new server ready all except for this. Thanks!

**Comment by TheLukeGuy** [comment]
Okay, now I'm getting all kinds of crazy errors for some reason. Running any command gives me:
`[20:39:06 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Xssentials v1.0-pre.4
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[patched_1.12.2.jar:git-Paper-1218]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1423) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$212/1106241765.run(Unknown Source) [patched_1.12.2.jar:git-Paper-1218]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1218]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at com.kkosyfarinis.spigot.xssentials.User.initializeUser(User.java:51) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.User.<init>(User.java:34) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.events.EventOnPlayerCommand.onPlayerCommand(EventOnPlayerCommand.java:30) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.EventListener.onPlayerCommand(EventListener.java:32) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[patched_1.12.2.jar:git-Paper-1218]
	... 18 more
`
Joining or leaving gives me
`[20:39:01 ERROR]: Could not pass event PlayerJoinEvent to Xssentials v1.0-pre.4
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.12.2.jar:git-Paper-1218]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1218]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:171) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:63) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:202) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1218]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1218]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at com.kkosyfarinis.spigot.xssentials.User.initializeUser(User.java:51) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.User.<init>(User.java:34) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.events.EventOnPlayerJoin.onPlayerJoin(EventOnPlayerJoin.java:20) ~[?:?]
	at com.kkosyfarinis.spigot.xssentials.EventListener.onPlayerJoin(EventListener.java:49) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.2.jar:git-Paper-1218]
	... 15 more
`

And all have to do with NullPointerExceptions and EventListener. Any idea why?

**Comment by TheLukeGuy** [comment]
**Second update,** I turned economy on and what'da you know? It works. I looked at line 51 in User.java and it defined the player's money so I tried turning the economy on. I'll leave this issue open so you can fix that issue, though. You can close it if you wish.

**Comment by KKosyfarinis** [comment]
Sorry for the late reply to this, I have been super busy lately with University, thus the slower updates. I've had 10 hours of university classes today, and my schedule is full at the moment. I will keep on doing stuff on Xssentials, as soon as the schedule 'cools' down a bit. 

Thanks for the report though, I will enable the Economy by default for the next update!

**Comment by TheLukeGuy** [comment]
Thanks!
